import { lazy, Suspense } from "react";
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./context/AuthProvider";
import { ErrorBoundary } from "./components/ErrorBoundary";
import { ProtectedRoute } from "./components/ProtectedRoute";
import { RouteFallback } from "./components/RouteFallback";
import { Seo } from "./components/Seo";

const Home = lazy(() => import("./pages/Home")); const About = lazy(() => import("./pages/About")); const Services = lazy(() => import("./pages/Services")); const Gallery = lazy(() => import("./pages/Gallery")); const Packages = lazy(() => import("./pages/Packages")); const Contact = lazy(() => import("./pages/Contact")); const Bookings = lazy(() => import("./pages/Bookings")); const Profile = lazy(() => import("./pages/Profile")); const CustomerLogin = lazy(() => import("./pages/CustomerLogin")); const CustomerSignup = lazy(() => import("./pages/CustomerSignup")); const AdminLogin = lazy(() => import("./pages/AdminLogin")); const AdminAccess = lazy(() => import("./pages/AdminAccess")); const AdminBookings = lazy(() => import("./pages/AdminBookings")); const AdminEnquiries = lazy(() => import("./pages/AdminEnquiries")); const AdminGallery = lazy(() => import("./pages/AdminGallery")); const AdminPackages = lazy(() => import("./pages/AdminPackages")); const AdminServices = lazy(() => import("./pages/AdminServices")); const NotFound = lazy(() => import("./pages/NotFound"));

export default function App() { return <BrowserRouter><AuthProvider><Seo /><Toaster position="top-right" /><ErrorBoundary><Suspense fallback={<RouteFallback />}><Routes><Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/services" element={<Services />} /><Route path="/gallery" element={<Gallery />} /><Route path="/packages" element={<Packages />} /><Route path="/contact" element={<Contact />} /><Route path="/booking" element={<Bookings />} /><Route path="/bookings" element={<Navigate replace to="/booking" />} /><Route path="/profile" element={<Profile />} /><Route path="/login" element={<CustomerLogin />} /><Route path="/signup" element={<CustomerSignup />} /><Route path="/admin/login" element={<AdminLogin />} /><Route path="/admin/access" element={<ProtectedRoute><AdminAccess /></ProtectedRoute>} /><Route path="/admin/bookings" element={<ProtectedRoute><AdminBookings /></ProtectedRoute>} /><Route path="/admin/enquiries" element={<ProtectedRoute><AdminEnquiries /></ProtectedRoute>} /><Route path="/admin/gallery" element={<ProtectedRoute><AdminGallery /></ProtectedRoute>} /><Route path="/admin/packages" element={<ProtectedRoute><AdminPackages /></ProtectedRoute>} /><Route path="/admin/services" element={<ProtectedRoute><AdminServices /></ProtectedRoute>} /><Route path="*" element={<NotFound />} /></Routes></Suspense></ErrorBoundary></AuthProvider></BrowserRouter>; }
