import { useState } from "react";
import toast from "react-hot-toast";
import { HiEnvelope, HiMapPin, HiPhone } from "react-icons/hi2";
import { MainLayout } from "../layouts/MainLayout";
import { PageHero } from "../components/PageHero";
import { Button, Input } from "../components/common";
import { createInquiry } from "../services/inquiryService";
import { useAuth } from "../hooks/useAuth";
const initialForm = { name: "", email: "", phone: "", message: "" };
export default function Contact() { const { user } = useAuth(); const [form, setForm] = useState(initialForm); const [submitting, setSubmitting] = useState(false); const update = ({ target }) => setForm((current) => ({ ...current, [target.name]: target.value })); const submit = async (event) => { event.preventDefault(); setSubmitting(true); try { await createInquiry(form); toast.success(user ? "Enquiry sent. Track replies in My Profile." : "Thank you — your enquiry has been sent."); setForm(initialForm); } catch (error) { toast.error(error.message); } finally { setSubmitting(false); } }; return <MainLayout><PageHero eyebrow="Let’s talk" title="An occasion worth remembering starts here." copy="Tell us a little about what you are planning. Our team will receive your enquiry directly." image="https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1800&q=85" /><section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#b89225]">Our studio</p><h2 className="font-display mt-4 text-4xl">Come say hello.</h2>{user && <p className="mt-4 rounded-xl bg-[#fff7df] p-4 text-sm text-[#73580f]">Your enquiry and team replies will appear in My Profile.</p>}<div className="mt-9 grid gap-6">{[[HiPhone, "Call us", "+91 90654 23192"], [HiEnvelope, "Email us", "mumtazDawat@gmail.com"], [HiMapPin, "Visit us", "MG Road, Bengaluru · by appointment"]].map(([Icon, title, detail]) => <div key={title} className="flex gap-4"><Icon className="mt-1 text-2xl text-[#b89225]" /><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-600">{detail}</p></div></div>)}</div></div><form onSubmit={submit} className="rounded-[1.5rem] bg-white p-7 shadow-sm md:p-10"><div className="grid gap-6 md:grid-cols-2"><Input label="Your name" name="name" value={form.name} onChange={update} required /><Input label="Email address" name="email" type="email" value={form.email} onChange={update} required /></div><div className="mt-6"><Input label="Phone number" name="phone" value={form.phone} onChange={update} /></div><label className="mt-6 block text-sm font-semibold">Tell us about your event<textarea required minLength="10" name="message" value={form.message} onChange={update} rows="5" className="mt-2 w-full rounded-lg border border-[#ded8ca] px-4 py-3" /></label><Button type="submit" disabled={submitting} className="mt-7 w-full">{submitting ? "Sending enquiry…" : "Send enquiry"}</Button></form></section></MainLayout>; }
