import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { HiCheck } from "react-icons/hi2";
import { MainLayout } from "../layouts/MainLayout";
import { PageHero } from "../components/PageHero";
import { Button } from "../components/common";
import { SectionHeading } from "../components/SectionHeading";
import { getPublicPackages } from "../services/packageService";
export default function Packages() { const [packages, setPackages] = useState([]); useEffect(() => { getPublicPackages().then(setPackages).catch((error) => toast.error(error.message)); }, []); return <MainLayout><PageHero eyebrow="Curated starting points" title="Choose a canvas for your occasion." copy="Each package is tailored around your venue, guest list, and personal style. Prices are indicative only." image="https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1800&q=85" /><section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHeading eyebrow="Our collection" title="Flexible by design, exceptional by nature." />{packages.length === 0 ? <p className="py-12 text-center text-slate-500">Our curated packages will be available soon.</p> : <div className="grid gap-6 lg:grid-cols-3">{packages.map((pkg) => <article key={pkg._id} className={`relative rounded-[1.5rem] p-8 ${pkg.featured ? "bg-[#142235] text-white shadow-2xl" : "border border-[#e7e1d4] bg-white"}`}>{pkg.featured && <span className="absolute -top-3 rounded-full bg-[#d4af37] px-4 py-1 text-xs font-bold uppercase tracking-wider text-[#142235]">Most loved</span>}<p className="text-xs font-bold uppercase tracking-[.16em] text-[#b89225]">{pkg.eyebrow || pkg.description}</p><h2 className="font-display mt-4 text-4xl">{pkg.name}</h2><p className="font-display mt-6 text-3xl text-[#d4af37]">{pkg.priceType === "custom" ? "Custom" : `₹${pkg.price.toLocaleString("en-IN")}`}</p><p className={`mt-2 text-sm ${pkg.featured ? "text-slate-300" : "text-slate-500"}`}>{pkg.maxGuests}+ guests · {pkg.duration} hours</p><ul className={`my-8 grid gap-4 border-y py-7 text-sm ${pkg.featured ? "border-white/15 text-slate-200" : "border-[#eee8dc] text-slate-600"}`}>{pkg.inclusions.map((item) => <li className="flex gap-3" key={item}><HiCheck className="shrink-0 text-lg text-[#b89225]" />{item}</li>)}</ul><Link to="/booking" state={{ package: pkg }}><Button variant={pkg.featured ? "gold" : "outline"} className="w-full">Book this package</Button></Link></article>)}</div>}</section></MainLayout>; }
