import express from "express";
import * as controller from "../controllers/serviceController.js";
import { requireActiveAdmin, verifyToken } from "../middleware/auth.js";
import { validateBody, validateObjectId } from "../middleware/validateRequest.js";
const router = express.Router();
const fields = ["name", "description", "category", "customCategory", "icon", "image", "price", "duration", "maxGuests", "features", "availability", "isActive"];
router.get("/", controller.list);
router.get("/:id", validateObjectId(), controller.getById);
router.post("/", verifyToken, requireActiveAdmin, validateBody({ allowedFields: fields, requiredFields: ["name", "description", "category", "image", "price", "duration", "maxGuests"] }), controller.create);
router.put("/:id", verifyToken, requireActiveAdmin, validateObjectId(), validateBody({ allowedFields: fields }), controller.update);
router.delete("/:id", verifyToken, requireActiveAdmin, validateObjectId(), controller.remove);
export default router;
